module.exports = {
    CREATE_REMINDER_MQ_QUEUE: 'CREATE_REMINDER',
    PROCESS_REMINDER_MQ_QUEUE:"PROCESS_REMINDER",
    SEND_REMINDER_MQ_QUEUE:"SEND_REMINDER",
    UPDATE_REMINDER_MQ_QUEUE:"UPDATE_REMINDER",
    REMOVE_REMINDER_BY_USER_ID_MQ_QUEUE:"REMOVE_REMINDER_BY_USER_ID",
  };
  