module.exports = {

    PENDING_REMINDER_STATUS:"PENDING",
    SENT_REMINDER_STATUS:"SENT",
  
    ANNUAL_REMINDER_REPEAT:"ANNUAL",
    QUARTERLY_REMINDER_REPEAT:"QUARTERLY",
    MONTHLY_REMINDER_REPEAT:"MONTHLY",
    WEEKLY_REMINDER_REPEAT:"WEEKLY",
    DAILY_REMINDER_REPEAT:"DAILY",
  };
  